using Microsoft.EntityFrameworkCore.Migrations;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Data.Migrations
{
    /// <inheritdoc />
    public partial class IdentityLongKeys : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropForeignKey(
                name: "FK_User_Bet",
                table: "Bet");

            migrationBuilder.DropTable(
                name: "Users");

            // The Identity key columns participate in foreign keys. PostgreSQL refuses to
            // retype a column while a foreign key ties it to a column of a different type,
            // so the Identity FKs are dropped here and recreated once every key is bigint.
            migrationBuilder.Sql(@"ALTER TABLE ""AspNetRoleClaims"" DROP CONSTRAINT ""FK_AspNetRoleClaims_AspNetRoles_RoleId"";");
            migrationBuilder.Sql(@"ALTER TABLE ""AspNetUserClaims"" DROP CONSTRAINT ""FK_AspNetUserClaims_AspNetUsers_UserId"";");
            migrationBuilder.Sql(@"ALTER TABLE ""AspNetUserLogins"" DROP CONSTRAINT ""FK_AspNetUserLogins_AspNetUsers_UserId"";");
            migrationBuilder.Sql(@"ALTER TABLE ""AspNetUserRoles"" DROP CONSTRAINT ""FK_AspNetUserRoles_AspNetRoles_RoleId"";");
            migrationBuilder.Sql(@"ALTER TABLE ""AspNetUserRoles"" DROP CONSTRAINT ""FK_AspNetUserRoles_AspNetUsers_UserId"";");
            migrationBuilder.Sql(@"ALTER TABLE ""AspNetUserTokens"" DROP CONSTRAINT ""FK_AspNetUserTokens_AspNetUsers_UserId"";");

            // Existing Identity rows were created with GUID string keys that cannot be cast to
            // bigint. Because the foreign keys above were just dropped, cascading deletes will not
            // fire, so every dependent table is cleared explicitly in dependency order. Bets are
            // removed too since they reference users that cannot survive the key conversion.
            // A Development admin is re-seeded at startup.
            migrationBuilder.Sql(@"DELETE FROM ""BetResult"";");
            migrationBuilder.Sql(@"DELETE FROM ""Bet"";");
            migrationBuilder.Sql(@"DELETE FROM ""AspNetUserRoles"";");
            migrationBuilder.Sql(@"DELETE FROM ""AspNetUserClaims"";");
            migrationBuilder.Sql(@"DELETE FROM ""AspNetUserLogins"";");
            migrationBuilder.Sql(@"DELETE FROM ""AspNetUserTokens"";");
            migrationBuilder.Sql(@"DELETE FROM ""AspNetRoleClaims"";");
            migrationBuilder.Sql(@"DELETE FROM ""AspNetUsers"";");
            migrationBuilder.Sql(@"DELETE FROM ""AspNetRoles"";");

            // Bet.UserId: integer -> bigint is an implicit cast, so EF's generated SQL is fine.
            migrationBuilder.AlterColumn<long>(
                name: "UserId",
                table: "Bet",
                type: "bigint",
                nullable: false,
                oldClrType: typeof(int),
                oldType: "integer");

            // text -> bigint is not an implicit cast in PostgreSQL; an explicit USING clause is required.
            migrationBuilder.Sql(@"ALTER TABLE ""AspNetUserTokens"" ALTER COLUMN ""UserId"" TYPE bigint USING ""UserId""::bigint;");

            migrationBuilder.Sql(@"ALTER TABLE ""AspNetUsers"" ALTER COLUMN ""Id"" TYPE bigint USING ""Id""::bigint;");
            migrationBuilder.Sql(@"ALTER TABLE ""AspNetUsers"" ALTER COLUMN ""Id"" DROP DEFAULT;");
            migrationBuilder.Sql(@"ALTER TABLE ""AspNetUsers"" ALTER COLUMN ""Id"" ADD GENERATED BY DEFAULT AS IDENTITY;");

            migrationBuilder.AddColumn<string>(
                name: "Name",
                table: "AspNetUsers",
                type: "text",
                nullable: false,
                defaultValue: "");

            migrationBuilder.AddColumn<string>(
                name: "RefreshToken",
                table: "AspNetUsers",
                type: "text",
                nullable: true);

            migrationBuilder.Sql(@"ALTER TABLE ""AspNetUserRoles"" ALTER COLUMN ""RoleId"" TYPE bigint USING ""RoleId""::bigint;");
            migrationBuilder.Sql(@"ALTER TABLE ""AspNetUserRoles"" ALTER COLUMN ""UserId"" TYPE bigint USING ""UserId""::bigint;");
            migrationBuilder.Sql(@"ALTER TABLE ""AspNetUserLogins"" ALTER COLUMN ""UserId"" TYPE bigint USING ""UserId""::bigint;");
            migrationBuilder.Sql(@"ALTER TABLE ""AspNetUserClaims"" ALTER COLUMN ""UserId"" TYPE bigint USING ""UserId""::bigint;");

            migrationBuilder.Sql(@"ALTER TABLE ""AspNetRoles"" ALTER COLUMN ""Id"" TYPE bigint USING ""Id""::bigint;");
            migrationBuilder.Sql(@"ALTER TABLE ""AspNetRoles"" ALTER COLUMN ""Id"" DROP DEFAULT;");
            migrationBuilder.Sql(@"ALTER TABLE ""AspNetRoles"" ALTER COLUMN ""Id"" ADD GENERATED BY DEFAULT AS IDENTITY;");

            migrationBuilder.Sql(@"ALTER TABLE ""AspNetRoleClaims"" ALTER COLUMN ""RoleId"" TYPE bigint USING ""RoleId""::bigint;");

            // Recreate the Identity foreign keys now that all key columns are bigint.
            migrationBuilder.Sql(@"ALTER TABLE ""AspNetRoleClaims"" ADD CONSTRAINT ""FK_AspNetRoleClaims_AspNetRoles_RoleId"" FOREIGN KEY (""RoleId"") REFERENCES ""AspNetRoles""(""Id"") ON DELETE CASCADE;");
            migrationBuilder.Sql(@"ALTER TABLE ""AspNetUserClaims"" ADD CONSTRAINT ""FK_AspNetUserClaims_AspNetUsers_UserId"" FOREIGN KEY (""UserId"") REFERENCES ""AspNetUsers""(""Id"") ON DELETE CASCADE;");
            migrationBuilder.Sql(@"ALTER TABLE ""AspNetUserLogins"" ADD CONSTRAINT ""FK_AspNetUserLogins_AspNetUsers_UserId"" FOREIGN KEY (""UserId"") REFERENCES ""AspNetUsers""(""Id"") ON DELETE CASCADE;");
            migrationBuilder.Sql(@"ALTER TABLE ""AspNetUserRoles"" ADD CONSTRAINT ""FK_AspNetUserRoles_AspNetRoles_RoleId"" FOREIGN KEY (""RoleId"") REFERENCES ""AspNetRoles""(""Id"") ON DELETE CASCADE;");
            migrationBuilder.Sql(@"ALTER TABLE ""AspNetUserRoles"" ADD CONSTRAINT ""FK_AspNetUserRoles_AspNetUsers_UserId"" FOREIGN KEY (""UserId"") REFERENCES ""AspNetUsers""(""Id"") ON DELETE CASCADE;");
            migrationBuilder.Sql(@"ALTER TABLE ""AspNetUserTokens"" ADD CONSTRAINT ""FK_AspNetUserTokens_AspNetUsers_UserId"" FOREIGN KEY (""UserId"") REFERENCES ""AspNetUsers""(""Id"") ON DELETE CASCADE;");

            migrationBuilder.AddForeignKey(
                name: "FK_User_Bet",
                table: "Bet",
                column: "UserId",
                principalTable: "AspNetUsers",
                principalColumn: "Id");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropForeignKey(
                name: "FK_User_Bet",
                table: "Bet");

            migrationBuilder.DropColumn(
                name: "Name",
                table: "AspNetUsers");

            migrationBuilder.DropColumn(
                name: "RefreshToken",
                table: "AspNetUsers");

            // Drop the Identity foreign keys before retyping the key columns back to text.
            migrationBuilder.Sql(@"ALTER TABLE ""AspNetRoleClaims"" DROP CONSTRAINT ""FK_AspNetRoleClaims_AspNetRoles_RoleId"";");
            migrationBuilder.Sql(@"ALTER TABLE ""AspNetUserClaims"" DROP CONSTRAINT ""FK_AspNetUserClaims_AspNetUsers_UserId"";");
            migrationBuilder.Sql(@"ALTER TABLE ""AspNetUserLogins"" DROP CONSTRAINT ""FK_AspNetUserLogins_AspNetUsers_UserId"";");
            migrationBuilder.Sql(@"ALTER TABLE ""AspNetUserRoles"" DROP CONSTRAINT ""FK_AspNetUserRoles_AspNetRoles_RoleId"";");
            migrationBuilder.Sql(@"ALTER TABLE ""AspNetUserRoles"" DROP CONSTRAINT ""FK_AspNetUserRoles_AspNetUsers_UserId"";");
            migrationBuilder.Sql(@"ALTER TABLE ""AspNetUserTokens"" DROP CONSTRAINT ""FK_AspNetUserTokens_AspNetUsers_UserId"";");

            // Retype the keys back to text/integer. PostgreSQL needs explicit USING clauses for
            // these casts, and the IDENTITY generation on AspNetUsers.Id and AspNetRoles.Id must be
            // dropped before the column can be changed away from an integer type.
            migrationBuilder.Sql(@"ALTER TABLE ""Bet"" ALTER COLUMN ""UserId"" TYPE integer USING ""UserId""::integer;");
            migrationBuilder.Sql(@"ALTER TABLE ""AspNetUserTokens"" ALTER COLUMN ""UserId"" TYPE text USING ""UserId""::text;");

            migrationBuilder.Sql(@"ALTER TABLE ""AspNetUsers"" ALTER COLUMN ""Id"" DROP IDENTITY IF EXISTS;");
            migrationBuilder.Sql(@"ALTER TABLE ""AspNetUsers"" ALTER COLUMN ""Id"" TYPE text USING ""Id""::text;");

            migrationBuilder.Sql(@"ALTER TABLE ""AspNetUserRoles"" ALTER COLUMN ""RoleId"" TYPE text USING ""RoleId""::text;");
            migrationBuilder.Sql(@"ALTER TABLE ""AspNetUserRoles"" ALTER COLUMN ""UserId"" TYPE text USING ""UserId""::text;");
            migrationBuilder.Sql(@"ALTER TABLE ""AspNetUserLogins"" ALTER COLUMN ""UserId"" TYPE text USING ""UserId""::text;");
            migrationBuilder.Sql(@"ALTER TABLE ""AspNetUserClaims"" ALTER COLUMN ""UserId"" TYPE text USING ""UserId""::text;");

            migrationBuilder.Sql(@"ALTER TABLE ""AspNetRoles"" ALTER COLUMN ""Id"" DROP IDENTITY IF EXISTS;");
            migrationBuilder.Sql(@"ALTER TABLE ""AspNetRoles"" ALTER COLUMN ""Id"" TYPE text USING ""Id""::text;");

            migrationBuilder.Sql(@"ALTER TABLE ""AspNetRoleClaims"" ALTER COLUMN ""RoleId"" TYPE text USING ""RoleId""::text;");

            // Recreate the Identity foreign keys now that the key columns are text again.
            migrationBuilder.Sql(@"ALTER TABLE ""AspNetRoleClaims"" ADD CONSTRAINT ""FK_AspNetRoleClaims_AspNetRoles_RoleId"" FOREIGN KEY (""RoleId"") REFERENCES ""AspNetRoles""(""Id"") ON DELETE CASCADE;");
            migrationBuilder.Sql(@"ALTER TABLE ""AspNetUserClaims"" ADD CONSTRAINT ""FK_AspNetUserClaims_AspNetUsers_UserId"" FOREIGN KEY (""UserId"") REFERENCES ""AspNetUsers""(""Id"") ON DELETE CASCADE;");
            migrationBuilder.Sql(@"ALTER TABLE ""AspNetUserLogins"" ADD CONSTRAINT ""FK_AspNetUserLogins_AspNetUsers_UserId"" FOREIGN KEY (""UserId"") REFERENCES ""AspNetUsers""(""Id"") ON DELETE CASCADE;");
            migrationBuilder.Sql(@"ALTER TABLE ""AspNetUserRoles"" ADD CONSTRAINT ""FK_AspNetUserRoles_AspNetRoles_RoleId"" FOREIGN KEY (""RoleId"") REFERENCES ""AspNetRoles""(""Id"") ON DELETE CASCADE;");
            migrationBuilder.Sql(@"ALTER TABLE ""AspNetUserRoles"" ADD CONSTRAINT ""FK_AspNetUserRoles_AspNetUsers_UserId"" FOREIGN KEY (""UserId"") REFERENCES ""AspNetUsers""(""Id"") ON DELETE CASCADE;");
            migrationBuilder.Sql(@"ALTER TABLE ""AspNetUserTokens"" ADD CONSTRAINT ""FK_AspNetUserTokens_AspNetUsers_UserId"" FOREIGN KEY (""UserId"") REFERENCES ""AspNetUsers""(""Id"") ON DELETE CASCADE;");

            migrationBuilder.CreateTable(
                name: "Users",
                columns: table => new
                {
                    Id = table.Column<int>(type: "integer", nullable: false)
                        .Annotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn),
                    Name = table.Column<string>(type: "text", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_Users", x => x.Id);
                });

            migrationBuilder.AddForeignKey(
                name: "FK_User_Bet",
                table: "Bet",
                column: "UserId",
                principalTable: "Users",
                principalColumn: "Id");
        }
    }
}
