import { defineConfig } from 'vitepress'

export default defineConfig({
  title: 'WorldCup System',
  description: 'Project planning, roadmap, and change reviews',
  cleanUrls: true,
  ignoreDeadLinks: true,
  themeConfig: {
    nav: [
      { text: 'Dashboard', link: '/' },
      { text: 'Roadmap', link: '/roadmap' },
      { text: 'Changes', link: '/changes-review' },
      { text: 'API Status', link: '/api-status' },
    ],
    sidebar: [
      {
        text: 'Project',
        items: [
          { text: 'Dashboard', link: '/' },
          { text: 'System Overview', link: '/overview' },
          { text: 'Completion Roadmap', link: '/roadmap' },
          { text: 'Dev Workflow', link: '/workflow' },
          { text: 'API Status', link: '/api-status' },
          { text: 'Data Model', link: '/data-model' },
          { text: 'Changes Review', link: '/changes-review' },
        ],
      },
      {
        text: 'Phase change logs',
        collapsed: false,
        items: [
          { text: 'Phase 1 — Identity', link: '/changes/phase-1-identity' },
          { text: 'Phase 2 — Tournament Setup', link: '/changes/phase-2-tournament-setup' },
          { text: 'Phase 3 — Match Lifecycle', link: '/changes/phase-3-match-lifecycle' },
          { text: 'Phase 4 — Betting', link: '/changes/phase-4-betting' },
          { text: 'Phase 5 — Frontend SPA', link: '/changes/phase-5-frontend-spa' },
          { text: 'Phase 6 — Quality & Ops', link: '/changes/phase-6-quality-ops' },
          { text: 'Phase 7 — Bugfixes', link: '/changes/phase-7-bugfixes' },
          { text: 'Phase 8 — Dashboards', link: '/changes/phase-8-dashboards' },
          { text: 'Phase 9 — Ops Close-Out', link: '/changes/phase-9-ops-closeout' },
          { text: 'Phase 10 — Match Sync (Task 1)', link: '/changes/phase-10-match-sync' },
          { text: 'Phase 10 — Fixtures UX (Task 2)', link: '/changes/phase-10-fixtures-ux' },
          { text: 'Phase 10 — Styling (Task 3)', link: '/changes/phase-10-styling' },
          { text: 'Phase 10 — Cleanup (Task 4)', link: '/changes/phase-10-cleanup' },
          { text: 'Phase 10 — Planned backlog', link: '/changes/phase-10-planned' },
          { text: 'Phase 11 — External stage (Task 1)', link: '/changes/phase-11-external-stage' },
          { text: 'Phase 11 — Timeline provider (Task 2)', link: '/changes/phase-11-timeline-provider' },
          { text: 'Phase 11 — Player resolve (Task 3)', link: '/changes/phase-11-player-resolve' },
          { text: 'Phase 11 — Scorer apply (Task 4)', link: '/changes/phase-11-scorer-apply' },
          { text: 'Phase 11 — Sync wire (Task 5)', link: '/changes/phase-11-sync-wire' },
          { text: 'Phase 11 — Backfill (Task 6)', link: '/changes/phase-11-backfill' },
          { text: 'Phase 11 — Recent events honesty (Task 7)', link: '/changes/phase-11-recent-events-honesty' },
          { text: 'Phase 11 — Tests gate (Task 8)', link: '/changes/phase-11-tests-gate' },
          { text: 'Phase 11 — Planned backlog', link: '/changes/phase-11-planned' },
          { text: 'Phase 12 — Draw (Task 1)', link: '/changes/phase-12-draw' },
          { text: 'Phase 12 — Group sim (Task 2)', link: '/changes/phase-12-group-sim' },
          { text: 'Phase 12 — Bracket (Task 3)', link: '/changes/phase-12-bracket' },
          { text: 'Phase 12 — Tests gate (Task 4)', link: '/changes/phase-12-tests-gate' },
          { text: 'Phase 12 — 2030 Simulation (planned)', link: '/changes/phase-12-planned' },
          { text: 'Whole-project upload gate', link: '/changes/whole-project-upload-gate' },
          { text: 'Phase 13 — Company model (Task 2)', link: '/changes/phase-13-company-model' },
          { text: 'Phase 13 — Company API (Task 3)', link: '/changes/phase-13-company-api' },
          { text: 'Phase 13 — Leaderboard scope (Task 4)', link: '/changes/phase-13-leaderboard-scope' },
          { text: 'Phase 13 — SPA company UX (Task 5)', link: '/changes/phase-13-spa' },
          { text: 'Phase 13 — Tests gate (Task 6)', link: '/changes/phase-13-tests-gate' },
          { text: 'Phase 13 — Company competitions (planned)', link: '/changes/phase-13-planned' },
          { text: 'Phase 14 — Secrets (Task 2)', link: '/changes/phase-14-secrets' },
          { text: 'Phase 14 — CORS/JWT (Task 3)', link: '/changes/phase-14-cors' },
          { text: 'Phase 14 — Compose (Task 4)', link: '/changes/phase-14-compose' },
          { text: 'Phase 14 — SPA prod (Task 5)', link: '/changes/phase-14-spa-prod' },
          { text: 'Phase 14 — Migrate/smoke (Task 6)', link: '/changes/phase-14-migrate-smoke' },
          { text: 'Phase 14 — Gate (Task 7)', link: '/changes/phase-14-gate' },
          { text: 'Phase 14 — Deploy Readiness (planned)', link: '/changes/phase-14-planned' },
          { text: 'WC 2026 Live Data', link: '/changes/wc2026-live-data' },
          { text: 'Remove Demo Seed', link: '/changes/remove-demo-seed' },
        ],
      },
    ],
    search: {
      provider: 'local',
    },
    outline: {
      level: [2, 3],
    },
  },
})
